### ISSUE TITLE
Duplicated submodule inclusion?

### ISSUE THREAD

**Issue by fei4xu** [skui-org/skui#20]
Hi,

When I was clone the submodules, I found that the submodule inclusion is like this:
```sh
skui
  -ci @ 89caad7
  -cmake @ 1916030
  -3rdparty @ 0be8f0d
    -ci @ 9a12be1
    -cmake @ a3b38ef
    -skia @ 1698b32
```
I was confused a little bit.
1) `ci` and `cmake` are directly included as submodule in `skui` but then indirectly included in `3rdparty` repo, are they redundant?
2) the commits of `ci` and `cmake` in the direct submodule and the recursive submodule are not same, for example, `ci` has 89caad7 in direct inclusion but 9a12be1 in recursive inclusion, are they designed to be like that?

Thanks
Fei

**Comment by rubenvb** [comment]
They are necessary, albeit indeed a bit duplicated, see [your other issue](https://github.com/skui-org/skui/issues/19#issuecomment-809734468) for more explanation.
